name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: apple/swift-actions/setup-swift@v1
        with:
          swift-version: '6.1'
      - name: Run tests
        run: swift test --xunit-output TestResults.xml
      - name: Upload test results
        uses: actions/upload-test-results@v2
        with:
          files: TestResults.xml
